name: dbt - CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "models/**"
      - "macros/**"
      - "seeds/**"
      - "data-tests/**"
      - "analyses/**"
      - "snapshots/**"
      - "dbt_project.yml"
      - "packages.yml"
      - "package-lock.yml"
      - "profiles.yml"

jobs:
  build:
    name: dbt Build & Test on MotherDuck
    runs-on: ubuntu-latest

    env:
      JAFFLE_SHOP_DB_PATH: ${{ secrets.JAFFLE_SHOP_DB_PATH }}
      MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}
      DBT_SCHEMA: pr-${{ github.event.pull_request.number }}

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
      - name: Install uv
        run: python3 -m pip install uv
      - name: Install dbt
        run: uv pip install dbt-core dbt-duckdb duckdb==1.4.4 --system
      - name: Install dbt packages
        run: dbt deps
      - name: Run dbt models
        run: dbt run --target dev
      - name: Run dbt tests
        run: dbt test --target dev
      - name: Upload dbt artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dbt-target
          path: target/
