name: dbt - Seed

on:
  push:
    branches:
      - main
    paths:
      - "seeds/**"

jobs:
  seed:
    name: dbt Seed on MotherDuck
    runs-on: ubuntu-latest

    env:
      JAFFLE_SHOP_DB_PATH: ${{ secrets.JAFFLE_SHOP_DB_PATH }}
      MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}

    steps:
      - uses: "actions/checkout@v4"
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.12"
      - name: Install uv
        run: python3 -m pip install uv
      - name: Install dbt
        run: uv pip install dbt-core dbt-duckdb duckdb==1.4.4 --system
      - name: Install dbt packages
        run: dbt deps
      - name: Seed source data
        run: dbt seed --vars '{load_source_data: true}'
